version: '3.3'
volumes:
  data:
services:
  db:
    image: mysql:5
    ports:
    - "3306:3306"
    volumes:
    - data:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=volcano_visit
  app:
    image: phpmyadmin/phpmyadmin:latest
    links:
    - db
    ports:
    - 80:80
    environment:
    - PMA_ARBITRARY=1
  memcache:
    image: memcached:alpine
    ports:
      - "11211:11211"
